services:
  salary-service:
    build:
      context: .
    ports:
      - "8082:8017"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./Database/Data/salairedb;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on: []


