services:

  h2db:
    image: 1000kit/h2
    container_name: h2db
    environment:
      - H2_USER=idd
      - H2_PASSWORD=
      - H2_CONSOLE_ENABLED=true
      - H2_OPTIONS=-ifNotExists -webAllOthers
    ports:
      - "9092:9092"  # Expose the H2 TCP connection port

    restart: unless-stopped

  salairems:
    build: .
    image: salairems-image
    container_name: salairems-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:salairedb
      - SPRING_DATASOURCE_USERNAME=idd
      - SPRING_DATASOURCE_PASSWORD=
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    networks:
      - sae3
    ports:
      - "8017:8017"  # Map the port inside the container to your local machine
    depends_on:
      - h2db

networks:
  sae3:
    driver: bridge


