version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pointage_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql

  eureka:
    image: ghadamejrii/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 30s
      timeout: 10s
      retries: 5

  pointage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pointage-service
    ports:
      - "8081:8080"  # Port exposé pour Pointage-Service
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/pointage_db
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
      - eureka.client.service-url.default-zone=http://eureka:8761/eureka/
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
      - eureka.instance.lease-renewal-interval-in-seconds=30
      - eureka.instance.lease-expiration-duration-in-seconds=90
    depends_on:
      - mysql
      - eureka

  gateway:
    image: oussema/gateway:latest
    container_name: gateway
    ports:
      - "8090:8090"  # Port pour accéder à la passerelle API
    environment:
      - eureka.client.service-url.default-zone=http://eureka:8761/eureka/
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
    depends_on:
      - eureka

volumes:
  mysql_data:
    driver: local
